name: fashione_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  flutter_snake_navigationbar: ^0.6.1
  dartz: ^0.10.1
  http: ^1.1.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "#f9f9f9"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
